/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: http.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "http.pb-c.h"
void   http_msg__header__init
                     (HttpMsg__Header         *message)
{
  static HttpMsg__Header init_value = HTTP_MSG__HEADER__INIT;
  *message = init_value;
}
void   http_msg__init
                     (HttpMsg         *message)
{
  static HttpMsg init_value = HTTP_MSG__INIT;
  *message = init_value;
}
size_t http_msg__get_packed_size
                     (const HttpMsg *message)
{
  assert(message->base.descriptor == &http_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t http_msg__pack
                     (const HttpMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &http_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t http_msg__pack_to_buffer
                     (const HttpMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &http_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HttpMsg *
       http_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HttpMsg *)
     protobuf_c_message_unpack (&http_msg__descriptor,
                                allocator, len, data);
}
void   http_msg__free_unpacked
                     (HttpMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &http_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor http_msg__header__field_descriptors[2] =
{
  {
    "header_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HttpMsg__Header, header_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(HttpMsg__Header, has_header_value),
    offsetof(HttpMsg__Header, header_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned http_msg__header__field_indices_by_name[] = {
  0,   /* field[0] = header_name */
  1,   /* field[1] = header_value */
};
static const ProtobufCIntRange http_msg__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor http_msg__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HttpMsg.Header",
  "Header",
  "HttpMsg__Header",
  "",
  sizeof(HttpMsg__Header),
  2,
  http_msg__header__field_descriptors,
  http_msg__header__field_indices_by_name,
  1,  http_msg__header__number_ranges,
  (ProtobufCMessageInit) http_msg__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor http_msg__field_descriptors[12] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HttpMsg, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_major",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HttpMsg, http_major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_minor",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HttpMsg, http_minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_length",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(HttpMsg, has_content_length),
    offsetof(HttpMsg, content_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(HttpMsg, has_method),
    offsetof(HttpMsg, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status_code",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(HttpMsg, has_status_code),
    offsetof(HttpMsg, status_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encoding",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(HttpMsg, has_encoding),
    offsetof(HttpMsg, encoding),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HttpMsg, url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "headers",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HttpMsg, n_headers),
    offsetof(HttpMsg, headers),
    &http_msg__header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(HttpMsg, has_body),
    offsetof(HttpMsg, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HttpMsg, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_decoding",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(HttpMsg, has_is_decoding),
    offsetof(HttpMsg, is_decoding),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned http_msg__field_indices_by_name[] = {
  9,   /* field[9] = body */
  3,   /* field[3] = content_length */
  6,   /* field[6] = encoding */
  8,   /* field[8] = headers */
  1,   /* field[1] = http_major */
  2,   /* field[2] = http_minor */
  11,   /* field[11] = is_decoding */
  4,   /* field[4] = method */
  10,   /* field[10] = path */
  5,   /* field[5] = status_code */
  0,   /* field[0] = type */
  7,   /* field[7] = url */
};
static const ProtobufCIntRange http_msg__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 10 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor http_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HttpMsg",
  "HttpMsg",
  "HttpMsg",
  "",
  sizeof(HttpMsg),
  12,
  http_msg__field_descriptors,
  http_msg__field_indices_by_name,
  2,  http_msg__number_ranges,
  (ProtobufCMessageInit) http_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
